import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { ConnectSocialAccountCommand } from './connect-social-account.command';
import {
  SocialAccountRepository,
  SOCIAL_ACCOUNT_REPOSITORY,
} from '../../domain/repositories/social-account.repository';
import { SocialAccount } from '../../domain/entities/social-account.entity';
import { SocialPublisherMock } from '../../infrastructure/external-api/social-publisher.mock';
import { SocialAccountResponseDto } from '../dtos/social-account-response.dto';
import { Inject } from '@nestjs/common';

@CommandHandler(ConnectSocialAccountCommand)
export class ConnectSocialAccountHandler implements ICommandHandler<ConnectSocialAccountCommand> {
  constructor(
    @Inject(SOCIAL_ACCOUNT_REPOSITORY)
    private readonly accountRepository: SocialAccountRepository,
    private readonly publisherMock: SocialPublisherMock,
  ) {}

  async execute(command: ConnectSocialAccountCommand): Promise<SocialAccountResponseDto> {
    const existing = await this.accountRepository.findByPlatform(command.organizationId, command.platform);

    if (existing) {
      existing.updateTokens(command.accessToken, command.refreshToken, command.expiresAt);
      await this.accountRepository.save(existing);
      return SocialAccountResponseDto.fromPersistence(existing);
    }

    let profileData: Record<string, any>;
    try {
      profileData = await this.publisherMock.getProfile(command.platform, command.accessToken);
    } catch {
      return SocialAccountResponseDto.fromFallback('', command);
    }

    const account = new SocialAccount(
      '', // ID will be generated by Mongo
      command.organizationId,
      command.platform,
      command.platformUserId,
      command.accessToken,
      command.refreshToken || null,
      command.expiresAt || null,
      profileData,
      new Date(),
      new Date(),
    );

    await this.accountRepository.save(account);
    return SocialAccountResponseDto.fromPersistence(account);
  }
}
